spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aqy?allowMultiQuries=true&autoReconnect=true&failOverReadOnly=false&serverTimeZone=Asia/ShangHai
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver