spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aqy?allowMultiQuries=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    graphql:
      spring:
        web:
          servlet: debug
    web: debug
    com:
      example:
        javagraphqlapi:
          dao: debug
      mysql: debug
    org:
      springframework:
        jdbc: debug
      apache:
        ibatis: debug
      mybatis:
        spring: debug



# 关联了 GraphQLController
graphql:
  url: /local